# Generated by Django 3.2.7 on 2021-09-11 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('upfront_commission_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('trial_commission_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
